### ISSUE TITLE
Fails to fetch triggers with Radius

### ISSUE THREAD

**Issue by daentech** [localz/Spotz3-Android-SDK#2]
We have a Spot with a Geofence and radius on it, as well as a beacon with a radius. At least one of these Radii isn't being parsed correctly.

```
{
	"spotz": [{
		"spotId": "<SPOT_ID>",
		"siteId": "<SITE_ID>",
		"name": "Tag Name",
		"tags": [],
		"trigger": {
			"type": "within",
			"attributes": {
				"exit_beacons": 1,
				"enter_beacons": 1,
				"exit_radius_cm": 100,
				"enter_radius_cm": 100
			}
		},
		"ranging": 0,
		"beacons": [{
			"beaconId": "<BEACON_ID>",
			"uuid": "<BEACON_ID>",
			"major": 2,
			"minor": 1,
			"txPower": -59
		}],
		"attributes": {
			"OBJECT_ID": "1"
		}
	}],
	"site": {
		"siteId": "<SITE_ID>",
		"geofence": {
			"longitude": -0.09745976878662077,
			"latitude ": 51.504691683873915,
			"radius ": 100
		}
	}
}


EventReceiver@129018045  E  onGeofenceEvent onError
                         E  java.lang.NumberFormatException: Invalid int: "100.0"
                         E      at java.lang.Integer.invalidInt(Integer.java:138)
                         E      at java.lang.Integer.parse(Integer.java:410)
                         E      at java.lang.Integer.parseInt(Integer.java:367)
                         E      at java.lang.Integer.parseInt(Integer.java:334)
                         E      at java.lang.Integer.valueOf(Integer.java:525)
                         E      at com.localz.spotz.sdk.models.Trigger.getEnterRadius(Trigger.java:61)
                         E      at com.localz.spotz.sdk.models.Trigger.getTrigger(Trigger.java:43)
                         E      at com.localz.spotz.sdk.models.Spot.getSpot(Spot.java:79)
                         E      at com.localz.spotz.sdk.SpotEventReceiver.getSiteSpotzSync(SpotEventReceiver.java:555)
                         E      at com.localz.spotz.sdk.SpotEventReceiver.enterSite(SpotEventReceiver.java:83)
                         E      at com.localz.spotz.sdk.SpotGeofenceEventReceiver$1$2.run(SpotGeofenceEventReceiver.java:118)
                         E      at rx.util.async.operators.OperatorFromFunctionals$1.call(OperatorFromFunctionals.java:52)
                         E      at rx.util.async.operators.OperatorFromFunctionals$InvokeAsync.call(OperatorFromFunctionals.java:73)
                         E      at rx.util.async.operators.OperatorFromFunctionals$InvokeAsync.call(OperatorFromFunctionals.java:62)
                         E      at rx.Observable.unsafeSubscribe(Observable.java:8098)
                         E      at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
                         E      at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                         E      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                         E      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                         E      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.
                            java:269)
                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                         E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                         E      at java.lang.Thread.run(Thread.java:818)
```

It looks like when the radius is coming out of the database it isn't an int, but is instead a "NUMBER" in SQLite. Integer.parseInt is falling over because It isn't expecting `"100.0"`, an invalid int.

**Comment by alekseychugaev** [comment]
Fixed in version 3.0.4 of SDK

**Comment by daentech** [comment]
Thanks for the update. It looks like I'm now missing a dependency with the updated version.

`Caused by: java.lang.ClassNotFoundException: Didn't find class "com.localz.proximity.ble.Logger"`

Is there a package I can include to get that? I tried including the:
`compile 'com.localz.proximity.ble:ble-sdk-android:1.1.2@aar`

line, but I can't compile now (I'm targeting Java 8. Not sure if that would cause a problem)

**Comment by alekseychugaev** [comment]
Hi @daentech, you'll need
