### ISSUE TITLE
Strict Mode Violation

### ISSUE THREAD

**Issue by JustinTullgren** [localz/Spotz3-Android-SDK#8]
Hi,

I am seeing a strict mode violation from the sdk:
```

 StrictMode policy violation; ~duration=131 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=23 violation=2
                                                 at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1137)
                                                 at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:202)
                                                 at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:222)
                                                 at com.localz.spotz.sdk.api.utils.ObscuredSharedPreferences.getBoolean(ObscuredSharedPreferences.java:188)
                                                 at com.localz.spotz.sdk.SpotzStorage.getDebugFlag(SpotzStorage.java:340)
                                                 at com.localz.spotz.sdk.Spotz.readDebugFlag(Spotz.java:2201)
                                                 at com.localz.spotz.sdk.Spotz.initialize(Spotz.java:1293)
                                                 at com.thunderhead.android.demo.customerfirst.spotz.SpotzGeoLocationManager.register(SpotzGeoLocationManager.java:18)
                                                 at com.thunderhead.android.demo.customerfirst.CustomerFirstApplication.onCreate(CustomerFirstApplication.java:94)
                                                 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5010)
                                                 at android.app.ActivityThread.access$1600(ActivityThread.java:172)
                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1482)
                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                 at android.os.Looper.loop(Looper.java:145)
                                                 at android.app.ActivityThread.main(ActivityThread.java:5835)
                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

```

Is this a known issue?

**Comment by alekseychugaev** [comment]
Hi @JustinTullgren,
Thanks for your feedback.
We use shared preferences to store some configuration parameters, that's why you receive this strict mode violation. We will address it in one of future releases.
